### ISSUE TITLE
Missing Right Endpoint (EU)

### ISSUE THREAD

**Issue by ghost** [singer-io/tap-mixpanel#21]
Hi all,

Thanks for the work on this project! Currently I'm trying to move data from Mixpanel into my DWH, but I have difficulties as my end points are different than those used in this project.

Mixpanel created different API endpoints for those that keep there date within the EU. (See endpoints below).

![image](https://user-images.githubusercontent.com/78882043/107773694-510ae300-6d3e-11eb-97ee-aa513aa55383.png)

Would it be possible to also add these endpoints as an option, so I can use them within my project?

Thanks!!

Roman

**Comment by prijendev** [comment]
@ghost We provided support of EU endpoint in [PR#39](https://github.com/singer-io/tap-mixpanel/pull/39). So, can we close this issue?

**Comment by kethan1122** [comment]
Closing this issue as the tap now supports EU sub_domain
