### ISSUE TITLE
error: unrecognized arguments: --discover

### ISSUE THREAD

**Issue by ehuebner** [singer-io/tap-mixpanel#8]
Hi,
when I run:
`~/.virtualenvs/tap-mixpanel/bin/tap-mixpanel --config tap_mixpanel_config.json --discover > properties.json`
I get:
`tap-mixpanel: error: unrecognized arguments: --discover`

The discover agrument also does not appear in the man, from:
`~/.virtualenvs/tap-mixpanel/bin/tap-mixpanel -h`
I get:
```usage: tap-mixpanel [-h] -c CONFIG [-s STATE]
optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Config file
  -s STATE, --state STATE
                        State file
usage: tap-mixpanel [-h] -c CONFIG [-s STATE]
```

**Comment by prijendev** [comment]
@ehuebner We looked into this and found that tap is working fine with `--discover`. So, can we close this issue if it is resolved?

**Comment by kethan1122** [comment]
Going to close this as the issue seems to be resolved and stale
